import type { ClosetItem, Product, UserProfile } from "@/lib/types";

export const userProfile: UserProfile = {
  name: "Maya",
  budget: 250,
  style: ["Minimalist", "Polished", "Secondhand-friendly"],
  colors: ["Black", "Cream", "Navy", "Denim"],
  sizingHistory: [
    "Aster Studio: M kept 4/5 times",
    "Noma: size 8 preferred",
    "European shoes: size 39",
  ],
};

const leatherBreakdown = [
  { label: "Price fairness", score: 94, detail: "34% below comparable listings" },
  { label: "Closet compatibility", score: 88, detail: "Builds 7 outfits from items you own" },
  { label: "Fit confidence", score: 93, detail: "Your kept size is available" },
  { label: "Cost per wear", score: 91, detail: "Projected at $4.83 per wear" },
  { label: "Resale value", score: 89, detail: "Expected to retain 62% after one year" },
  { label: "Trend durability", score: 96, detail: "Core silhouette, low trend decay" },
  { label: "Return risk", score: 86, detail: "Low risk based on fit memory" },
  { label: "Circularity", score: 84, detail: "Secondhand alternatives available" },
];

export const products: Product[] = [
  {
    id: "aster-leather-jacket",
    name: "Sculpted leather jacket",
    brand: "Aster Studio",
    category: "Jacket",
    color: "Black",
    price: 348,
    originalPrice: 525,
    resalePrice: 218,
    score: 91,
    recommendation: "Buy now",
    scoreLabel: "Strong buy",
    description: "A softly structured lambskin jacket with a cropped, architectural line.",
    imagePosition: "62% 36%",
    breakdown: leatherBreakdown,
  },
  {
    id: "ora-linen-dress",
    name: "Bias linen column dress",
    brand: "Ora",
    category: "Dress",
    color: "Cream",
    price: 184,
    originalPrice: 240,
    resalePrice: 112,
    score: 86,
    recommendation: "Buy secondhand",
    scoreLabel: "Worth finding",
    description: "A breathable, fluid summer dress cut to layer easily.",
    imagePosition: "50% 62%",
    breakdown: leatherBreakdown.map((item, index) => ({ ...item, score: item.score - (index % 3) - 4 })),
  },
  {
    id: "selene-shoulder-bag",
    name: "Arc shoulder bag",
    brand: "Selene",
    category: "Bag",
    color: "Navy",
    price: 690,
    originalPrice: 690,
    resalePrice: 420,
    score: 78,
    recommendation: "Bid lower",
    scoreLabel: "Good, not urgent",
    description: "A compact curved shoulder bag in polished navy calfskin.",
    imagePosition: "76% 58%",
    breakdown: leatherBreakdown.map((item, index) => ({ ...item, score: item.score - 8 - (index % 4) })),
  },
  {
    id: "form-court-sneaker",
    name: "Form 02 court sneaker",
    brand: "Common Form",
    category: "Shoes",
    color: "White",
    price: 165,
    originalPrice: 220,
    resalePrice: 74,
    score: 84,
    recommendation: "Buy now",
    scoreLabel: "Smart staple",
    description: "Low-profile leather sneakers with a clean, low-contrast sole.",
    imagePosition: "68% 78%",
    breakdown: leatherBreakdown.map((item, index) => ({ ...item, score: item.score - 5 - (index % 2) })),
  },
  {
    id: "noma-wedding-dress",
    name: "Draped occasion dress",
    brand: "Noma",
    category: "Dress",
    color: "Navy",
    price: 278,
    originalPrice: 365,
    resalePrice: 168,
    score: 82,
    recommendation: "Wait for price drop",
    scoreLabel: "Waitlist it",
    description: "An asymmetric draped dress designed for warm-weather occasions.",
    imagePosition: "44% 42%",
    breakdown: leatherBreakdown.map((item, index) => ({ ...item, score: item.score - 6 - (index % 5) })),
  },
  {
    id: "vintage-denim",
    name: "Vintage 1990 denim jacket",
    brand: "Archive No. 8",
    category: "Jacket",
    color: "Denim",
    price: 124,
    originalPrice: 210,
    resalePrice: 98,
    score: 69,
    recommendation: "Skip — closet overlap",
    scoreLabel: "Too familiar",
    description: "A washed indigo trucker jacket with subtle wear and a relaxed shoulder.",
    imagePosition: "30% 70%",
    breakdown: leatherBreakdown.map((item, index) => ({
      ...item,
      score: index === 1 ? 42 : item.score - 12,
      detail: index === 1 ? "You already own 2 close substitutes" : item.detail,
    })),
  },
];

export const closetItems: ClosetItem[] = [
  { id: "cropped-jacket", name: "Black cropped jacket", category: "Jacket", color: "Black", wears: 19, lastWorn: "8 days ago", resaleValue: 88, listingPrice: 105, compatibility: 97 },
  { id: "linen-shirt", name: "White linen shirt", category: "Top", color: "Cream", wears: 27, lastWorn: "3 days ago", resaleValue: 42, listingPrice: 54, compatibility: 92 },
  { id: "straight-jeans", name: "Straight-leg jeans", category: "Bottom", color: "Denim", wears: 34, lastWorn: "Yesterday", resaleValue: 64, listingPrice: 78, compatibility: 95 },
  { id: "loafers", name: "Neutral loafers", category: "Shoes", color: "Cream", wears: 16, lastWorn: "12 days ago", resaleValue: 118, listingPrice: 145, compatibility: 88 },
  { id: "slip-dress", name: "Ink slip dress", category: "Dress", color: "Navy", wears: 7, lastWorn: "74 days ago", resaleValue: 136, listingPrice: 165, compatibility: 81 },
  { id: "tote", name: "Structured tote bag", category: "Bag", color: "Black", wears: 11, lastWorn: "96 days ago", resaleValue: 205, listingPrice: 245, compatibility: 76 },
];

export const featuredProduct = products[0];
